name: Deploy executables

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build executable Nix
        run: |
          python -m pip install .
          python -m pip install pyinstaller
          pyinstaller src/build.spec

      - uses: actions/upload-artifact@v4
        with:
          name: pyspecan
          path: dist/

      - name: Build executable Win
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v4
        with:
          name: pyspecan.exe
          path: src/dist/windows

  pyinstaller-upload:
    runs-on: ubuntu-latest
    needs:
      - pyinstaller-build
    permissions:
      contents: write

    steps:
      - name: Retrieve artifact Nix
        uses: actions/download-artifact@v4
        with:
          name: pyspecan
          path: dist/

      - name: Retrieve artifact Win
        uses: actions/download-artifact@v4
        with:
          name: pyspecan.exe
          path: dist/

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/pyspecan
            dist/pyspecan.exe
